### ISSUE TITLE
Add to Moodle.org's plugins database

### ISSUE THREAD

**Issue by vaughany** [netspotau/moodle-block_poll#1]
It would be handy if you could register this plugin on Moodle.org's plugins database, so users of Moodle 2.x (such as myself) could more easily find it. It didn't take long for Google to find this repo but it would fit nicely with Moodle 2.5's auto update/install system.

Cheers.

**Comment by aolley** [comment]
Now on moodle.org :)
https://moodle.org/plugins/view.php?plugin=block_poll
